"""GenerationPlan Pydantic v2 model — output contract of the pipeline planning step."""
from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict


class OutputLayer(StrEnum):
    """Where a generated artifact is installed."""

    GLOBAL = "global"
    PROJECT = "project"
    # PROJECT_ROOT writes outside .claude/ — at the project root itself.
    # Used for files Claude Code reads from the repo root (e.g. .mcp.json).
    PROJECT_ROOT = "project_root"


class Artifact(BaseModel):
    """A single file to be generated by the TemplateRegistry."""

    model_config = ConfigDict(extra="forbid")

    target_path: str
    template_id: str
    context: dict[str, object]
    layer: OutputLayer
    # When True, the generator skips this artifact if the target already exists,
    # leaving user-owned content (e.g. CONSTITUTION.md) byte-untouched.
    write_once: bool = False


class GenerationPlan(BaseModel):
    """Full generation plan produced by the pipeline for a given ProjectSpec."""

    model_config = ConfigDict(extra="forbid")

    project_name: str
    domain: str
    artifacts: list[Artifact]
